services:
  database:
    container_name: database
    image: postgres:latest
    restart: always
    env_file:
      - configs/config.env
    ports:
      - "5000:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    env_file:
      - configs/config.env
    environment:
      - DB_HOST=database
      - DB_PORT=5432
  backend1:
    build: ./testUtils/backend1
    environment:
      - PORT=8081
    ports:
      - 8081:8081
  backend2:
    build: ./testUtils/backend2
    environment:
      - PORT=8082
    ports:
      - 8082:8082
  backend3:
    build: ./testUtils/backend3
    environment:
      - PORT=8083
    ports:
      - 8083:8083
  test_utils:
    container_name: test_utils
    build:
      context: .
      dockerfile: DockerfileNetworks
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8085:8085"
      - "8086:8086"
      - "8087:8087"
      - "8088:8088"
      - "8089:8089"
      - "8090:8090"
      - "8084:8084"